jenkins-master:
  {{- if eq .Values.registry "nuarch"}}
  image: jenkins/jenkins:lts-slim
  {{- else }}
  image: ${registryPath}/jenkins/jenkins:lts-slim
  {{- end }}
  scale: 1
  ports:
    - "${jenkinsPort}:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${volumeWork}:/var/jenkins_home
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: ${forceImagePull}
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    {{- if eq .Values.useHostAffinity "true" }}
    io.rancher.scheduler.affinity:host_label: ${hostAffinityLabel}
    {{- end }}
  environment:
    TZ: "America/New_York"
    JENKINS_OPTS: "--prefix=/${pathPrefix}"
  user: jenkins:${dockerGroupId}
