.catalog:
  name: Jenkins
  version: lts-slim-latest
  description: |
    Template for deplopying Jenkins CI management server.
  questions:

# Registry

  - variable: "registry"
    label: "Registry"
    description: "DSNY, nuArch, or custom registry"
    type: enum
    options:
      - nuarch
      - other
    required: true
    default: nuarch

  - variable: "registryPath"
    label: "Registry path (upto, but not including image name and version)"
    description: "Used only when 'other' selected for regsitry.  Examples: msplva-dsnsmt71.csc.nycnet:5000/dsny for DSNY or gcr.io/dnsy-eis"
    type: string
    required: false
    default: ""

  - variable: "forceImagePull"
    label: "Force image pull"
    description: "Ignore cache and pull image from repository."
    type: "boolean"
    required: true
    default: false

# Hosts

  - variable: "useHostAffinity"
    label: "Use host affinity"
    description: "Schedule instance to a host with specified label"
    type: "boolean"
    required: true
    default: true

  - variable: "hostAffinityLabel"
    label: "Host label for Affinity"
    description: "Only used when using host affinity.  Example label: type=persist"
    type: "string"
    required: false
    default: ci-master=true

# Deployment settings

  - variable: "pathPrefix"
    type: "string"
    label: "Path Prefix"
    description: "Path prefix for accessing Jenkins"
    default: "jenkins"
    required: true

  - variable: "jenkinsPort"
    type: "int"
    label: "Port Number"
    description: "Port where Jenkins will listen on?"
    default: 9090
    required: true

  - variable: "dockerGroupId"
    description: "Id of docker group on host"
    label: "Docker GID:"
    required: true
    default: "999"
    type: "string"

  - variable: "volumeWork"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/mnt/disks/data-1/jenkins"
    type: "string"
