jenkins-swarm-client-smart:
  {{- if eq .Values.registry "nuarch"}}
  image: docker.nuarch.io/jenkins-swarm-client-for-android:0.1.0
  {{- else }}
  image: ${registryPath}/jenkins-swarm-client-for-android:0.1.0
  {{- end }}
  scale: ${scale}
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: ${forceImagePull}
    {{- if eq .Values.useHostAffinity "true" }}
    io.rancher.scheduler.affinity:host_label: ${hostAffinityLabel}
    {{- end }}
  external_links:
    - "${jenkinsMaster}:jenkins-master"
  environment:
    TZ: "America/New_York"
    PROFILES: "rancher"
    JENKINS_PREFIX: "/${pathPrefix}"
    JENKINS_PORT: "8080"
    JENKINS_PASS: "${jenkinsPass}"
    JENKINS_USER: "${jenkinsUser}"
    SWARM_EXECUTORS: "${executors}"
